//These are constraints written (generated directly in vivado) on the basis of ZEDBOARD FPGA.

set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sw2]
set_property IOSTANDARD LVCMOS33 [get_ports sw3]
set_property IOSTANDARD LVCMOS33 [get_ports sw4]
set_property IOSTANDARD LVCMOS33 [get_ports sw6]
set_property IOSTANDARD LVCMOS33 [get_ports sw5]
set_property IOSTANDARD LVCMOS33 [get_ports sw7]
set_property PACKAGE_PIN P16 [get_ports rst]
set_property PACKAGE_PIN H22 [get_ports sw2]
set_property PACKAGE_PIN F21 [get_ports sw3]
set_property PACKAGE_PIN H19 [get_ports sw4]
set_property PACKAGE_PIN H18 [get_ports sw5]
set_property PACKAGE_PIN H17 [get_ports sw6]
set_property PACKAGE_PIN M15 [get_ports sw7]

set_property IOSTANDARD LVCMOS33 [get_ports door_open]
set_property PACKAGE_PIN U14 [get_ports door_open]
